import cloudinary from 'cloudinary';
import { file } from 'tmp';

const upds =function uplcloud(){
    cloudinary.config({
        cloud_name: 'djf1tigyw', 
        api_key: '117152564788648', 
        api_secret: 'OvWS3KxSzfQ-E8L5LA1GgQfd9Sc'
    }); file
    const file=req.files
    const tagname=req.files.FormFieldName 
    cloudinary.v2.uploader.upload(file, { tags:tagname }, function (err, image) {
        console.log();
        console.log("** File Upload");
        if (err) { console.warn(err); }
        console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
        console.log("* " + image.public_id);
        console.log("* " + image.url);
        waitForAllUploads("pizza", err, image);
      });
}
export {upds}

